"""add carryover flag, enrollment management

Revision ID: e146bf6d53a8
Revises: 1a28cc12bfa6
Create Date: 2026-09-16 17:15:02.725517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e146bf6d53a8'
down_revision: Union[str, None] = '1a28cc12bfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column as nullable first
    op.add_column('enrollments', sa.Column('is_carryover', sa.Boolean(), nullable=True))

    # 2. Update existing rows to have a default value (False)
    op.execute("UPDATE enrollments SET is_carryover = FALSE")

    # 3. Alter the column to be NOT NULL
    op.alter_column('enrollments', 'is_carryover', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'is_carryover')
    # ### end Alembic commands ###
